name: build-check

on:
 pull_request:
  branches:
   - dev
   - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: check-out
     uses: actions/checkout@v4

   - name: set-up-node
     uses: actions/setup-node@v3
     with:
      node-version: 20

   - name: install pnpm
     run: npm install - pnpm

   - name: install-deps
     run: pnpm install

   - name: build
     run: npm run build
