name: build-check

on:
 pull_request:
  branches:
   - dev
   - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: check-out
     uses: actions/checkout@v4

   - name: install pnpm
     uses: pnpm/action-setup@v2
     with:
      version: 7
      run_install: false

   - name: set-up-node
     uses: actions/setup-node@v3
     with:
      node-version: 20
      cache: pnpm

   - name: install-deps
     run: pnpm install --frozen-lockfile

   - name: build
     run: npm run build
